### ISSUE TITLE
Feature Request: "rotate"

### ISSUE THREAD

**Issue by fwolfst** [ruby/matrix#19]
I miss a function to rotate a Matrix/Vector:
```ruby
m
# [ [ 1 2 3 ]
#   [ 4 5 6 ] ]
n = m.rotate_clockwise(1) # rotate clockwise, "one time"
n
# [ [ 4 1 ]
#   [ 5 2 ]
#   [ 6 3 ] ]
```

Excuse my rusty math brain, maybe it is already implemented but named differently, in which case the documentation might be improved to mention the word "rotate" :)

**Comment by marcandre** [comment]
Is there a (mathematical) use-case?

**Comment by fwolfst** [comment]
@marcandre I don't know about math (my matrix-days are long ago). My use case is in pattern-matching/finding algorithms.

**Comment by marcandre** [comment]
Got it.
I think it would be acceptable.
API I'd propose would be:
`Matrix#rotate_entries(quarter_turns)` where `quarter_turns` can be `:clockwise`, `:counter_clockwise`, `:half_turn`, or any integer (with `:clockwise` same as `1, 5, 9, -3, -7, ...`, etc.)

How does that sound? Would you care to provide a PR?

**Comment by fwolfst** [comment]
Along the lines of https://github.com/fwolfst/matrix ? Not sure if I will find more time to implement the case where a integer param is given.

**Comment by marcandre** [comment]
Yes, along those lines. Care must be taken about empty matrices ("0 by n" and "n by 0").

**Comment by fwolfst** [comment]
> Yes, along those lines. Care must be taken about empty matrices ("0 by n" and "n by 0").

Okay, on its way. Emptiness seems to need special care all over the place. Maybe I take a stab at the Numeric argument handling tomorrow. It is not very far away.

**Comment by fwolfst** [comment]
Pull Request #20 issued. Discussion should continue there I guess.

**Comment by fwolfst** [comment]
Afaiu, this made it into a release. Thanks.
