### ISSUE TITLE
Documentation missing on docs.ruby-lang.org

### ISSUE THREAD

**Issue by coffeejunk** [ruby/matrix#32]
I'm not sure if this is the right place but I noticed that the `matrix` documentation is missing on https://docs.ruby-lang.org/ starting with Ruby 3.1:

| version | link |  |
| ----- | ------ | --- |
| 2.7 | https://docs.ruby-lang.org/en/2.7.0/Matrix.html | ✅ |
| 3.0 | https://docs.ruby-lang.org/en/3.0/Matrix.html | ✅ |
| 3.1 | https://docs.ruby-lang.org/en/3.1/?search=matrix# | ❌ | 
| master | https://docs.ruby-lang.org/en/master/?search=matrix# | ❌ |

https://github.com/rubyapi/rubyapi/issues/1323

**Comment by hsbt** [comment]
Because `Matrix` has been extracted from ruby core.
